In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', 1000)

In [3]:
gompertz = pd.read_csv('CovidColombia.csv', low_memory=False, usecols= ['ID de caso', 'Fecha de notificación', 
                                                                        'Ciudad de ubicación', 
                                                                        'Departamento o Distrito '], 
                                                                        parse_dates=['Fecha de notificación'] )

In [4]:
gompertz.sort_values(by=['Fecha de notificación'],inplace=True)

In [5]:
gompertz.columns

Index(['ID de caso', 'Fecha de notificación', 'Ciudad de ubicación',
       'Departamento o Distrito '],
      dtype='object')

In [6]:
gompertz['Fecha de notificación']= gompertz['Fecha de notificación'].dt.floor('d')

In [7]:
gompertz

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,2,2020-03-06,Guadalajara de Buga,Valle del Cauca
2,3,2020-03-07,Medellín,Antioquia
6,7,2020-03-08,Cartagena de Indias,Cartagena D.T. y C.
8,9,2020-03-08,Bogotá D.C.,Bogotá D.C.
...,...,...,...,...
548855,548896,2020-08-24,Barranquilla,Barranquilla D.E.
548446,548487,2020-08-24,Rionegro,Antioquia
549220,549261,2020-08-24,Lérida,Tolima
548670,548711,2020-08-24,Rionegro,Antioquia
548680,548721,2020-08-24,Guarne,Antioquia

In [8]:
gompertz.loc[237959,'Fecha de notificación']

Timestamp('2020-07-18 00:00:00')

In [9]:
df = pd.DataFrame(gompertz['Fecha de notificación']).loc[0]
df

Fecha de notificación   2020-03-02
Name: 0, dtype: datetime64[ns]

In [10]:
a = gompertz.loc[0,'Fecha de notificación']

In [11]:
b = np.datetime64('today') 
b

numpy.datetime64('2020-08-25')

In [12]:
longitud = (b-a)/ np.timedelta64(1, 'D')
longitud=int(longitud)-1
longitud

175

In [13]:
df_fechas = pd.DataFrame(df).transpose()
df_fechas

  Fecha de notificación
0            2020-03-02

In [14]:
df_fechas['ID de caso']=0

In [15]:
df_fechas

  Fecha de notificación  ID de caso
0            2020-03-02           0

In [16]:
pd.to_datetime([df_fechas.loc[0,'Fecha de notificación']])

DatetimeIndex(['2020-03-02'], dtype='datetime64[ns]', freq=None)

In [17]:
(np.datetime64(df_fechas.loc[0, 'Fecha de notificación']) + np.timedelta64(1,'D'))

numpy.datetime64('2020-03-03T00:00:00.000000')

In [18]:
for i in range(1,longitud):
    df_fechas.loc[(i)] = [(np.datetime64(df_fechas.loc[i-1, 'Fecha de notificación']) + np.timedelta64(1,'D')),0]

In [19]:
df_fechas

    Fecha de notificación  ID de caso
0              2020-03-02           0
1              2020-03-03           0
2              2020-03-04           0
3              2020-03-05           0
4              2020-03-06           0
5              2020-03-07           0
6              2020-03-08           0
7              2020-03-09           0
8              2020-03-10           0
9              2020-03-11           0
10             2020-03-12           0
11             2020-03-13           0
12             2020-03-14           0
13             2020-03-15           0
14             2020-03-16           0
15             2020-03-17           0
16             2020-03-18           0
17             2020-03-19           0
18             2020-03-20           0
19             2020-03-21           0
20             2020-03-22           0
21             2020-03-23           0
22             2020-03-24           0
23             2020-03-25           0
24             2020-03-26           0
25             2020-03-27           0
26             2020-03-28           0
27             2020-03-29           0
28             2020-03-30           0
29             2020-03-31           0
30             2020-04-01           0
31             2020-04-02           0
32             2020-04-03           0
33             2020-04-04           0
34             2020-04-05           0
35             2020-04-06           0
36             2020-04-07           0
37             2020-04-08           0
38             2020-04-09           0
39             2020-04-10           0
40             2020-04-11           0
41             2020-04-12           0
42             2020-04-13           0
43             2020-04-14           0
44             2020-04-15           0
45             2020-04-16           0
46             2020-04-17           0
47             2020-04-18           0
48             2020-04-19           0
49             2020-04-20           0
50             2020-04-21           0
51             2020-04-22           0
52             2020-04-23           0
53             2020-04-24           0
54             2020-04-25           0
55             2020-04-26           0
56             2020-04-27           0
57             2020-04-28           0
58             2020-04-29           0
59             2020-04-30           0
60             2020-05-01           0
61             2020-05-02           0
62             2020-05-03           0
63             2020-05-04           0
64             2020-05-05           0
65             2020-05-06           0
66             2020-05-07           0
67             2020-05-08           0
68             2020-05-09           0
69             2020-05-10           0
70             2020-05-11           0
71             2020-05-12           0
72             2020-05-13           0
73             2020-05-14           0
74             2020-05-15           0
75             2020-05-16           0
76             2020-05-17           0
77             2020-05-18           0
78             2020-05-19           0
79             2020-05-20           0
80             2020-05-21           0
81             2020-05-22           0
82             2020-05-23           0
83             2020-05-24           0
84             2020-05-25           0
85             2020-05-26           0
86             2020-05-27           0
87             2020-05-28           0
88             2020-05-29           0
89             2020-05-30           0
90             2020-05-31           0
91             2020-06-01           0
92             2020-06-02           0
93             2020-06-03           0
94             2020-06-04           0
95             2020-06-05           0
96             2020-06-06           0
97             2020-06-07           0
98             2020-06-08           0
99             2020-06-09           0
100            2020-06-10           0
101            2020-06-11           0
102            2020-06-12           0
103            2020-06-13           0
104            2020-06-14           0
105            2020-06-15           0
106            2020-06-16           0
107            2020-06-17           0
108            2020-06-18           0
109            2020-06-19           0
110            2020-06-20           0
111            2020-06-21           0
112            2020-06-22           0
113            2020-06-23           0
114            2020-06-24           0
115            2020-06-25           0
116            2020-06-26           0
117            2020-06-27           0
118            2020-06-28           0
119            2020-06-29           0
120            2020-06-30           0
121            2020-07-01           0
122            2020-07-02           0
123            2020-07-03           0
124            2020-07-04           0
125            2020-07-05           0
126            2020-07-06           0
127            2020-07-07           0
128            2020-07-08           0
129            2020-07-09           0
130            2020-07-10           0
131            2020-07-11           0
132            2020-07-12           0
133            2020-07-13           0
134            2020-07-14           0
135            2020-07-15           0
136            2020-07-16           0
137            2020-07-17           0
138            2020-07-18           0
139            2020-07-19           0
140            2020-07-20           0
141            2020-07-21           0
142            2020-07-22           0
143            2020-07-23           0
144            2020-07-24           0
145            2020-07-25           0
146            2020-07-26           0
147            2020-07-27           0
148            2020-07-28           0
149            2020-07-29           0
150            2020-07-30           0
151            2020-07-31           0
152            2020-08-01           0
153            2020-08-02           0
154            2020-08-03           0
155            2020-08-04           0
156            2020-08-05           0
157            2020-08-06           0
158            2020-08-07           0
159            2020-08-08           0
160            2020-08-09           0
161            2020-08-10           0
162            2020-08-11           0
163            2020-08-12           0
164            2020-08-13           0
165            2020-08-14           0
166            2020-08-15           0
167            2020-08-16           0
168            2020-08-17           0
169            2020-08-18           0
170            2020-08-19           0
171            2020-08-20           0
172            2020-08-21           0
173            2020-08-22           0
174            2020-08-23           0

In [20]:
gompertz_Col=gompertz.append(df_fechas).sort_values(by=['Fecha de notificación'], ignore_index=True)

In [21]:
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.
1,0,2020-03-02,NaN,NaN
2,0,2020-03-03,NaN,NaN
3,0,2020-03-04,NaN,NaN
4,0,2020-03-05,NaN,NaN
...,...,...,...,...
551866,548487,2020-08-24,Rionegro,Antioquia
551867,548711,2020-08-24,Rionegro,Antioquia
551868,548721,2020-08-24,Guarne,Antioquia
551869,548901,2020-08-24,Barranquilla,Barranquilla D.E.
551870,549088,2020-08-24,El Carmen de Atrato,Chocó

In [22]:
longitud = gompertz_Col['ID de caso'].size
longitud

551871

In [23]:
for i in range(0, longitud):
    if gompertz_Col.loc[i, 'ID de caso'] == 0:
        pass
    else:
        gompertz_Col.loc[i, 'ID de caso'] = 1

In [24]:
#pd.to_datetime(gompertz_Col.loc[237958,'Fecha de notificación'], format='%Y-%m-%d')
#gompertz_Col.loc[237958, 'Fecha de notificación']

In [25]:
gompertz_Col['Acumulados']= 0
gompertz_Col['Día número']=0
gompertz_Col['Penetración real']=0
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.,0,0,0
1,0,2020-03-02,NaN,NaN,0,0,0
2,0,2020-03-03,NaN,NaN,0,0,0
3,0,2020-03-04,NaN,NaN,0,0,0
4,0,2020-03-05,NaN,NaN,0,0,0
...,...,...,...,...,...,...,...
551866,1,2020-08-24,Rionegro,Antioquia,0,0,0
551867,1,2020-08-24,Rionegro,Antioquia,0,0,0
551868,1,2020-08-24,Guarne,Antioquia,0,0,0
551869,1,2020-08-24,Barranquilla,Barranquilla D.E.,0,0,0
551870,1,2020-08-24,El Carmen de Atrato,Chocó,0,0,0

In [26]:
gompertz_Col.shape

(551871, 7)

In [27]:
gompertz_Col.loc[0, 'Acumulados']= gompertz_Col.loc[0, 'ID de caso']
for i in range(1, longitud):
    gompertz_Col.loc[i,'Acumulados'] = gompertz_Col.loc[i, 'ID de caso'] + gompertz_Col.loc[i-1, 'Acumulados']

In [28]:
gompertz_Col

,ID de caso,Fecha de notificación,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
0,1,2020-03-02,Bogotá D.C.,Bogotá D.C.,1,0,0
1,0,2020-03-02,NaN,NaN,1,0,0
2,0,2020-03-03,NaN,NaN,1,0,0
3,0,2020-03-04,NaN,NaN,1,0,0
4,0,2020-03-05,NaN,NaN,1,0,0
...,...,...,...,...,...,...,...
551866,1,2020-08-24,Rionegro,Antioquia,551692,0,0
551867,1,2020-08-24,Rionegro,Antioquia,551693,0,0
551868,1,2020-08-24,Guarne,Antioquia,551694,0,0
551869,1,2020-08-24,Barranquilla,Barranquilla D.E.,551695,0,0
551870,1,2020-08-24,El Carmen de Atrato,Chocó,551696,0,0

In [29]:
gompertz_Colombia = gompertz_Col.groupby('Fecha de notificación')[['ID de caso', 'Ciudad de ubicación',
       'Departamento o Distrito ', 'Acumulados', 'Día número',
       'Penetración real']].max()

In [30]:
gompertz_Colombia

,ID de caso,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
Fecha de notificación,,,,,,
2020-03-02,1,NaN,NaN,1,0,0
2020-03-03,0,NaN,NaN,1,0,0
2020-03-04,0,NaN,NaN,1,0,0
2020-03-05,0,NaN,NaN,1,0,0
2020-03-06,1,NaN,NaN,2,0,0
2020-03-07,1,NaN,NaN,3,0,0
2020-03-08,1,NaN,NaN,5,0,0
2020-03-09,1,NaN,NaN,8,0,0
2020-03-10,1,NaN,NaN,12,0,0
2020-03-11,1,NaN,NaN,20,0,0
2020-03-12,1,NaN,NaN,31,0,0
2020-03-13,1,NaN,NaN,44,0,0
2020-03-14,1,NaN,NaN,64,0,0
2020-03-15,1,NaN,NaN,83,0,0
2020-03-16,1,NaN,NaN,112,0,0
2020-03-17,1,NaN,NaN,154,0,0
2020-03-18,1,NaN,NaN,198,0,0
2020-03-19,1,NaN,NaN,267,0,0
2020-03-20,1,NaN,NaN,345,0,0
2020-03-21,1,NaN,NaN,425,0,0
2020-03-22,1,NaN,NaN,507,0,0
2020-03-23,1,NaN,NaN,601,0,0
2020-03-24,1,NaN,NaN,742,0,0
2020-03-25,1,NaN,NaN,904,0,0
2020-03-26,1,NaN,NaN,1063,0,0
2020-03-27,1,NaN,NaN,1223,0,0
2020-03-28,1,NaN,NaN,1389,0,0
2020-03-29,1,NaN,NaN,1528,0,0
2020-03-30,1,NaN,NaN,1722,0,0
2020-03-31,1,NaN,NaN,1912,0,0
2020-04-01,1,NaN,NaN,2107,0,0
2020-04-02,1,NaN,NaN,2273,0,0
2020-04-03,1,NaN,NaN,2460,0,0
2020-04-04,1,NaN,NaN,2620,0,0
2020-04-05,1,NaN,NaN,2721,0,0
2020-04-06,1,NaN,NaN,2873,0,0
2020-04-07,1,NaN,NaN,3030,0,0
2020-04-08,1,NaN,NaN,3156,0,0
2020-04-09,1,NaN,NaN,3298,0,0
2020-04-10,1,NaN,NaN,3419,0,0
2020-04-11,1,NaN,NaN,3667,0,0
2020-04-12,1,NaN,NaN,3824,0,0
2020-04-13,1,NaN,NaN,4010,0,0
2020-04-14,1,NaN,NaN,4248,0,0
2020-04-15,1,NaN,NaN,4416,0,0
2020-04-16,1,NaN,NaN,4671,0,0
2020-04-17,1,NaN,NaN,4849,0,0
2020-04-18,1,NaN,NaN,5054,0,0
2020-04-19,1,NaN,NaN,5275,0,0
2020-04-20,1,NaN,NaN,5492,0,0
2020-04-21,1,NaN,NaN,5711,0,0
2020-04-22,1,NaN,NaN,5959,0,0
2020-04-23,1,NaN,NaN,6261,0,0
2020-04-24,1,NaN,NaN,6567,0,0
2020-04-25,1,NaN,NaN,6872,0,0
2020-04-26,1,NaN,NaN,7125,0,0
2020-04-27,1,NaN,NaN,7533,0,0
2020-04-28,1,NaN,NaN,8048,0,0
2020-04-29,1,NaN,NaN,8429,0,0
2020-04-30,1,NaN,NaN,8904,0,0
2020-05-01,1,NaN,NaN,9371,0,0
2020-05-02,1,NaN,NaN,9832,0,0
2020-05-03,1,NaN,NaN,10227,0,0
2020-05-04,1,NaN,NaN,10737,0,0
2020-05-05,1,NaN,NaN,11528,0,0
2020-05-06,1,NaN,NaN,12283,0,0
2020-05-07,1,NaN,NaN,13057,0,0
2020-05-08,1,NaN,NaN,14037,0,0
2020-05-09,1,NaN,NaN,14780,0,0
2020-05-10,1,NaN,NaN,15251,0,0
2020-05-11,1,NaN,NaN,15984,0,0
2020-05-12,1,NaN,NaN,16806,0,0
2020-05-13,1,NaN,NaN,17651,0,0
2020-05-14,1,NaN,NaN,18712,0,0
2020-05-15,1,NaN,NaN,19690,0,0
2020-05-16,1,NaN,NaN,20597,0,0
2020-05-17,1,NaN,NaN,21439,0,0
2020-05-18,1,NaN,NaN,22640,0,0
2020-05-19,1,NaN,NaN,23802,0,0
2020-05-20,1,NaN,NaN,25197,0,0
2020-05-21,1,NaN,NaN,26561,0,0
2020-05-22,1,NaN,NaN,27977,0,0
2020-05-23,1,NaN,NaN,29401,0,0
2020-05-24,1,NaN,NaN,30307,0,0
2020-05-25,1,NaN,NaN,31466,0,0
2020-05-26,1,NaN,NaN,32983,0,0
2020-05-27,1,NaN,NaN,34350,0,0
2020-05-28,1,NaN,NaN,35759,0,0
2020-05-29,1,NaN,NaN,37173,0,0
2020-05-30,1,NaN,NaN,38473,0,0
2020-05-31,1,NaN,NaN,39516,0,0
2020-06-01,1,NaN,NaN,41258,0,0
2020-06-02,1,NaN,NaN,42908,0,0
2020-06-03,1,NaN,NaN,44799,0,0
2020-06-04,1,NaN,NaN,46583,0,0
2020-06-05,1,NaN,NaN,48598,0,0
2020-06-06,1,NaN,NaN,50401,0,0
2020-06-07,1,NaN,NaN,51871,0,0
2020-06-08,1,NaN,NaN,54398,0,0
2020-06-09,1,NaN,NaN,56819,0,0
2020-06-10,1,NaN,NaN,59606,0,0
2020-06-11,1,NaN,NaN,62564,0,0
2020-06-12,1,NaN,NaN,65518,0,0
2020-06-13,1,NaN,NaN,67994,0,0
2020-06-14,1,NaN,NaN,69658,0,0
2020-06-15,1,NaN,NaN,71547,0,0
2020-06-16,1,NaN,NaN,75295,0,0
2020-06-17,1,NaN,NaN,79283,0,0
2020-06-18,1,NaN,NaN,83174,0,0
2020-06-19,1,NaN,NaN,87177,0,0
2020-06-20,1,NaN,NaN,90655,0,0
2020-06-21,1,NaN,NaN,93262,0,0
2020-06-22,1,NaN,NaN,96209,0,0
2020-06-23,1,NaN,NaN,101261,0,0
2020-06-24,1,NaN,NaN,106358,0,0
2020-06-25,1,NaN,NaN,111542,0,0
2020-06-26,1,NaN,NaN,117135,0,0
2020-06-27,1,NaN,NaN,121811,0,0
2020-06-28,1,NaN,NaN,125383,0,0
2020-06-29,1,NaN,NaN,129209,0,0
2020-06-30,1,NaN,NaN,135223,0,0
2020-07-01,1,NaN,NaN,141487,0,0
2020-07-02,1,NaN,NaN,147762,0,0
2020-07-03,1,NaN,NaN,154685,0,0
2020-07-04,1,NaN,NaN,161040,0,0
2020-07-05,1,NaN,NaN,165674,0,0
2020-07-06,1,NaN,NaN,173012,0,0
2020-07-07,1,NaN,NaN,180068,0,0
2020-07-08,1,NaN,NaN,187938,0,0
2020-07-09,1,NaN,NaN,195061,0,0
2020-07-10,1,NaN,NaN,203220,0,0
2020-07-11,1,NaN,NaN,209828,0,0
2020-07-12,1,NaN,NaN,215174,0,0
2020-07-13,1,NaN,NaN,224652,0,0
2020-07-14,1,NaN,NaN,233800,0,0
2020-07-15,1,NaN,NaN,242453,0,0
2020-07-16,1,NaN,NaN,251848,0,0
2020-07-17,1,NaN,NaN,261545,0,0
2020-07-18,1,NaN,NaN,271008,0,0
2020-07-19,1,NaN,NaN,277272,0,0
2020-07-20,1,NaN,NaN,284161,0,0
2020-07-21,1,NaN,NaN,294530,0,0
2020-07-22,1,NaN,NaN,304842,0,0
2020-07-23,1,NaN,NaN,315251,0,0
2020-07-24,1,NaN,NaN,325667,0,0
2020-07-25,1,NaN,NaN,334986,0,0
2020-07-26,1,NaN,NaN,341785,0,0
2020-07-27,1,NaN,NaN,353818,0,0
2020-07-28,1,NaN,NaN,365529,0,0
2020-07-29,1,NaN,NaN,376248,0,0
2020-07-30,1,NaN,NaN,387074,0,0
2020-07-31,1,NaN,NaN,398297,0,0
2020-08-01,1,NaN,NaN,407478,0,0
2020-08-02,1,NaN,NaN,413686,0,0
2020-08-03,1,NaN,NaN,424464,0,0
2020-08-04,1,NaN,NaN,434631,0,0
2020-08-05,1,NaN,NaN,444564,0,0
2020-08-06,1,NaN,NaN,455920,0,0
2020-08-07,1,NaN,NaN,463451,0,0
2020-08-08,1,NaN,NaN,472054,0,0
2020-08-09,1,NaN,NaN,477496,0,0
2020-08-10,1,NaN,NaN,486840,0,0
2020-08-11,1,NaN,NaN,495890,0,0
2020-08-12,1,NaN,NaN,504040,0,0
2020-08-13,1,NaN,NaN,511950,0,0
2020-08-14,1,NaN,NaN,518906,0,0
2020-08-15,1,NaN,NaN,524049,0,0
2020-08-16,1,NaN,NaN,527455,0,0
2020-08-17,1,NaN,NaN,530952,0,0
2020-08-18,1,NaN,NaN,537297,0,0
2020-08-19,1,NaN,NaN,542845,0,0
2020-08-20,1,NaN,NaN,546933,0,0
2020-08-21,1,NaN,NaN,550039,0,0
2020-08-22,1,NaN,NaN,551296,0,0
2020-08-23,1,NaN,NaN,551686,0,0
2020-08-24,1,Rionegro,Tolima,551696,0,0

In [31]:
gompertz_Colombia.reset_index(inplace=True)

In [32]:
longitud = gompertz_Colombia['ID de caso'].size
longitud

176

In [33]:
gompertz_Colombia.columns

Index(['Fecha de notificación', 'ID de caso', 'Ciudad de ubicación',
       'Departamento o Distrito ', 'Acumulados', 'Día número',
       'Penetración real'],
      dtype='object')

In [34]:
gompertz_Colombia.loc[0, 'Día número'] = 1
for i in range(1, longitud):
    gompertz_Colombia.loc[i,'Día número'] = i+1
    gompertz_Colombia.loc[i,'Penetración real'] = gompertz_Colombia.loc[i, 'Acumulados']/ gompertz_Colombia.loc[longitud-1, 'Acumulados']

In [35]:
gompertz_Colombia

,Fecha de notificación,ID de caso,Ciudad de ubicación,Departamento o Distrito,Acumulados,Día número,Penetración real
0,2020-03-02,1,NaN,NaN,1,1,0.000000
1,2020-03-03,0,NaN,NaN,1,2,0.000002
2,2020-03-04,0,NaN,NaN,1,3,0.000002
3,2020-03-05,0,NaN,NaN,1,4,0.000002
4,2020-03-06,1,NaN,NaN,2,5,0.000004
5,2020-03-07,1,NaN,NaN,3,6,0.000005
6,2020-03-08,1,NaN,NaN,5,7,0.000009
7,2020-03-09,1,NaN,NaN,8,8,0.000015
8,2020-03-10,1,NaN,NaN,12,9,0.000022
9,2020-03-11,1,NaN,NaN,20,10,0.000036
10,2020-03-12,1,NaN,NaN,31,11,0.000056
11,2020-03-13,1,NaN,NaN,44,12,0.000080
12,2020-03-14,1,NaN,NaN,64,13,0.000116
13,2020-03-15,1,NaN,NaN,83,14,0.000150
14,2020-03-16,1,NaN,NaN,112,15,0.000203
15,2020-03-17,1,NaN,NaN,154,16,0.000279
16,2020-03-18,1,NaN,NaN,198,17,0.000359
17,2020-03-19,1,NaN,NaN,267,18,0.000484
18,2020-03-20,1,NaN,NaN,345,19,0.000625
19,2020-03-21,1,NaN,NaN,425,20,0.000770
20,2020-03-22,1,NaN,NaN,507,21,0.000919
21,2020-03-23,1,NaN,NaN,601,22,0.001089
22,2020-03-24,1,NaN,NaN,742,23,0.001345
23,2020-03-25,1,NaN,NaN,904,24,0.001639
24,2020-03-26,1,NaN,NaN,1063,25,0.001927
25,2020-03-27,1,NaN,NaN,1223,26,0.002217
26,2020-03-28,1,NaN,NaN,1389,27,0.002518
27,2020-03-29,1,NaN,NaN,1528,28,0.002770
28,2020-03-30,1,NaN,NaN,1722,29,0.003121
29,2020-03-31,1,NaN,NaN,1912,30,0.003466
30,2020-04-01,1,NaN,NaN,2107,31,0.003819
31,2020-04-02,1,NaN,NaN,2273,32,0.004120
32,2020-04-03,1,NaN,NaN,2460,33,0.004459
33,2020-04-04,1,NaN,NaN,2620,34,0.004749
34,2020-04-05,1,NaN,NaN,2721,35,0.004932
35,2020-04-06,1,NaN,NaN,2873,36,0.005208
36,2020-04-07,1,NaN,NaN,3030,37,0.005492
37,2020-04-08,1,NaN,NaN,3156,38,0.005721
38,2020-04-09,1,NaN,NaN,3298,39,0.005978
39,2020-04-10,1,NaN,NaN,3419,40,0.006197
40,2020-04-11,1,NaN,NaN,3667,41,0.006647
41,2020-04-12,1,NaN,NaN,3824,42,0.006931
42,2020-04-13,1,NaN,NaN,4010,43,0.007268
43,2020-04-14,1,NaN,NaN,4248,44,0.007700
44,2020-04-15,1,NaN,NaN,4416,45,0.008004
45,2020-04-16,1,NaN,NaN,4671,46,0.008467
46,2020-04-17,1,NaN,NaN,4849,47,0.008789
47,2020-04-18,1,NaN,NaN,5054,48,0.009161
48,2020-04-19,1,NaN,NaN,5275,49,0.009561
49,2020-04-20,1,NaN,NaN,5492,50,0.009955
50,2020-04-21,1,NaN,NaN,5711,51,0.010352
51,2020-04-22,1,NaN,NaN,5959,52,0.010801
52,2020-04-23,1,NaN,NaN,6261,53,0.011349
53,2020-04-24,1,NaN,NaN,6567,54,0.011903
54,2020-04-25,1,NaN,NaN,6872,55,0.012456
55,2020-04-26,1,NaN,NaN,7125,56,0.012915
56,2020-04-27,1,NaN,NaN,7533,57,0.013654
57,2020-04-28,1,NaN,NaN,8048,58,0.014588
58,2020-04-29,1,NaN,NaN,8429,59,0.015278
59,2020-04-30,1,NaN,NaN,8904,60,0.016139
60,2020-05-01,1,NaN,NaN,9371,61,0.016986
61,2020-05-02,1,NaN,NaN,9832,62,0.017821
62,2020-05-03,1,NaN,NaN,10227,63,0.018537
63,2020-05-04,1,NaN,NaN,10737,64,0.019462
64,2020-05-05,1,NaN,NaN,11528,65,0.020896
65,2020-05-06,1,NaN,NaN,12283,66,0.022264
66,2020-05-07,1,NaN,NaN,13057,67,0.023667
67,2020-05-08,1,NaN,NaN,14037,68,0.025443
68,2020-05-09,1,NaN,NaN,14780,69,0.026790
69,2020-05-10,1,NaN,NaN,15251,70,0.027644
70,2020-05-11,1,NaN,NaN,15984,71,0.028972
71,2020-05-12,1,NaN,NaN,16806,72,0.030462
72,2020-05-13,1,NaN,NaN,17651,73,0.031994
73,2020-05-14,1,NaN,NaN,18712,74,0.033917
74,2020-05-15,1,NaN,NaN,19690,75,0.035690
75,2020-05-16,1,NaN,NaN,20597,76,0.037334
76,2020-05-17,1,NaN,NaN,21439,77,0.038860
77,2020-05-18,1,NaN,NaN,22640,78,0.041037
78,2020-05-19,1,NaN,NaN,23802,79,0.043143
79,2020-05-20,1,NaN,NaN,25197,80,0.045672
80,2020-05-21,1,NaN,NaN,26561,81,0.048144
81,2020-05-22,1,NaN,NaN,27977,82,0.050711
82,2020-05-23,1,NaN,NaN,29401,83,0.053292
83,2020-05-24,1,NaN,NaN,30307,84,0.054934
84,2020-05-25,1,NaN,NaN,31466,85,0.057035
85,2020-05-26,1,NaN,NaN,32983,86,0.059785
86,2020-05-27,1,NaN,NaN,34350,87,0.062263
87,2020-05-28,1,NaN,NaN,35759,88,0.064816
88,2020-05-29,1,NaN,NaN,37173,89,0.067379
89,2020-05-30,1,NaN,NaN,38473,90,0.069736
90,2020-05-31,1,NaN,NaN,39516,91,0.071626
91,2020-06-01,1,NaN,NaN,41258,92,0.074784
92,2020-06-02,1,NaN,NaN,42908,93,0.077775
93,2020-06-03,1,NaN,NaN,44799,94,0.081202
94,2020-06-04,1,NaN,NaN,46583,95,0.084436
95,2020-06-05,1,NaN,NaN,48598,96,0.088088
96,2020-06-06,1,NaN,NaN,50401,97,0.091356
97,2020-06-07,1,NaN,NaN,51871,98,0.094021
98,2020-06-08,1,NaN,NaN,54398,99,0.098601
99,2020-06-09,1,NaN,NaN,56819,100,0.102990
100,2020-06-10,1,NaN,NaN,59606,101,0.108041
101,2020-06-11,1,NaN,NaN,62564,102,0.113403
102,2020-06-12,1,NaN,NaN,65518,103,0.118757
103,2020-06-13,1,NaN,NaN,67994,104,0.123245
104,2020-06-14,1,NaN,NaN,69658,105,0.126262
105,2020-06-15,1,NaN,NaN,71547,106,0.129686
106,2020-06-16,1,NaN,NaN,75295,107,0.136479
107,2020-06-17,1,NaN,NaN,79283,108,0.143708
108,2020-06-18,1,NaN,NaN,83174,109,0.150761
109,2020-06-19,1,NaN,NaN,87177,110,0.158016
110,2020-06-20,1,NaN,NaN,90655,111,0.164321
111,2020-06-21,1,NaN,NaN,93262,112,0.169046
112,2020-06-22,1,NaN,NaN,96209,113,0.174388
113,2020-06-23,1,NaN,NaN,101261,114,0.183545
114,2020-06-24,1,NaN,NaN,106358,115,0.192784
115,2020-06-25,1,NaN,NaN,111542,116,0.202180
116,2020-06-26,1,NaN,NaN,117135,117,0.212318
117,2020-06-27,1,NaN,NaN,121811,118,0.220794
118,2020-06-28,1,NaN,NaN,125383,119,0.227268
119,2020-06-29,1,NaN,NaN,129209,120,0.234203
120,2020-06-30,1,NaN,NaN,135223,121,0.245104
121,2020-07-01,1,NaN,NaN,141487,122,0.256458
122,2020-07-02,1,NaN,NaN,147762,123,0.267832
123,2020-07-03,1,NaN,NaN,154685,124,0.280381
124,2020-07-04,1,NaN,NaN,161040,125,0.291900
125,2020-07-05,1,NaN,NaN,165674,126,0.300299
126,2020-07-06,1,NaN,NaN,173012,127,0.313600
127,2020-07-07,1,NaN,NaN,180068,128,0.326390
128,2020-07-08,1,NaN,NaN,187938,129,0.340655
129,2020-07-09,1,NaN,NaN,195061,130,0.353566
130,2020-07-10,1,NaN,NaN,203220,131,0.368355
131,2020-07-11,1,NaN,NaN,209828,132,0.380333
132,2020-07-12,1,NaN,NaN,215174,133,0.390023
133,2020-07-13,1,NaN,NaN,224652,134,0.407203
134,2020-07-14,1,NaN,NaN,233800,135,0.423784
135,2020-07-15,1,NaN,NaN,242453,136,0.439468
136,2020-07-16,1,NaN,NaN,251848,137,0.456498
137,2020-07-17,1,NaN,NaN,261545,138,0.474074
138,2020-07-18,1,NaN,NaN,271008,139,0.491227
139,2020-07-19,1,NaN,NaN,277272,140,0.502581
140,2020-07-20,1,NaN,NaN,284161,141,0.515068
141,2020-07-21,1,NaN,NaN,294530,142,0.533863
142,2020-07-22,1,NaN,NaN,304842,143,0.552554
143,2020-07-23,1,NaN,NaN,315251,144,0.571422
144,2020-07-24,1,NaN,NaN,325667,145,0.590302
145,2020-07-25,1,NaN,NaN,334986,146,0.607193
146,2020-07-26,1,NaN,NaN,341785,147,0.619517
147,2020-07-27,1,NaN,NaN,353818,148,0.641328
148,2020-07-28,1,NaN,NaN,365529,149,0.662555
149,2020-07-29,1,NaN,NaN,376248,150,0.681984
150,2020-07-30,1,NaN,NaN,387074,151,0.701607
151,2020-07-31,1,NaN,NaN,398297,152,0.721950
152,2020-08-01,1,NaN,NaN,407478,153,0.738592
153,2020-08-02,1,NaN,NaN,413686,154,0.749844
154,2020-08-03,1,NaN,NaN,424464,155,0.769380
155,2020-08-04,1,NaN,NaN,434631,156,0.787809
156,2020-08-05,1,NaN,NaN,444564,157,0.805813
157,2020-08-06,1,NaN,NaN,455920,158,0.826397
158,2020-08-07,1,NaN,NaN,463451,159,0.840048
159,2020-08-08,1,NaN,NaN,472054,160,0.855642
160,2020-08-09,1,NaN,NaN,477496,161,0.865506
161,2020-08-10,1,NaN,NaN,486840,162,0.882443
162,2020-08-11,1,NaN,NaN,495890,163,0.898846
163,2020-08-12,1,NaN,NaN,504040,164,0.913619
164,2020-08-13,1,NaN,NaN,511950,165,0.927957
165,2020-08-14,1,NaN,NaN,518906,166,0.940565
166,2020-08-15,1,NaN,NaN,524049,167,0.949887
167,2020-08-16,1,NaN,NaN,527455,168,0.956061
168,2020-08-17,1,NaN,NaN,530952,169,0.962400
169,2020-08-18,1,NaN,NaN,537297,170,0.973900
170,2020-08-19,1,NaN,NaN,542845,171,0.983957
171,2020-08-20,1,NaN,NaN,546933,172,0.991367
172,2020-08-21,1,NaN,NaN,550039,173,0.996997
173,2020-08-22,1,NaN,NaN,551296,174,0.999275
174,2020-08-23,1,NaN,NaN,551686,175,0.999982
175,2020-08-24,1,Rionegro,Tolima,551696,176,1.000000

In [36]:

gompertz_Colombia.to_excel('GompertzCol.xlsx')

In [37]:
#import matplotlib.pyplot as plt
#from scipy.optimize import curve_fit
#import numpy as np

In [38]:
#def gompertz_model(x,a,b,c):
 #   return c*np.exp(-b*np.exp(-x/a))

#def func(x,a,b,c):
 #   return c*np.exp(-b*np.exp(-x/a))

In [39]:
#def func(x, a, b, c):
 #   return a * np.exp(-b * x) + c

In [40]:
#def expo_model(x,p,N0=3,x0=1):
 #   return N0*(1+p)**(x-x0)

#def logistic_model(x,a,b,c):
 #   return c/(1+np.exp(-(x-b)/a))

Define the data to be fit with some noise:

In [41]:
#xdata = gompertz_Colombia['Día número']
#y = func(xdata, gompertz_Colombia['Penetración real'])
#np.random.seed(1729)
#y_noise = 0.2 * np.random.normal(size=xdata.size)
#ydata = y + y_noise
#plt.plot(xdata, ydata, 'k-', label='data')

Define the data to be fit with some noise:

In [42]:
#popt, pcov = curve_fit(func, xdata, ydata)
#popt

#plt.plot(xdata, func(xdata, *popt), 'r-',
         #label='fit: a=%5.3f, b=%5.3f, c=%5.3f' % tuple(popt))

Constrain the optimization to the region of 0 <= a <= 3, 0 <= b <= 1 and 0 <= c <= 0.5:

In [43]:
#popt, pcov = curve_fit(func, xdata, ydata, bounds=(0, [3., 1., 0.5]))
#popt

#plt.plot(xdata, func(xdata, *popt), 'b--',
         #label='fit: a=%5.3f, b=%5.3f, c=%5.3f' % tuple(popt))

In [44]:
#plt.xlabel('x')
#plt.ylabel('y')
#plt.legend()
#plt.show()